/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author chaco
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        gestionarEmpleados = new javax.swing.JMenuItem();
        lblBienvenida = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuEmpleados = new javax.swing.JMenu();
        itemGestionEmpleados = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        itenGestionarProductos = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        itemGestionarProveedores = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemVentasPorFecha = new javax.swing.JMenuItem();
        itemProductosMasVendidos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        gestionarEmpleados.setText("gestionarEmpleados");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenida.setText("Bienvenido...");

        btnCerrarSesion.setText("Cerar Sesión");

        menuEmpleados.setText("Empleados");

        itemGestionEmpleados.setText("Gestionar Empleados");
        menuEmpleados.add(itemGestionEmpleados);

        menuBar.add(menuEmpleados);

        menuProductos.setText("Productos");

        itenGestionarProductos.setText("Gestionar Productos");
        menuProductos.add(itenGestionarProductos);

        menuBar.add(menuProductos);

        menuProveedores.setText("Proveedores");
        menuProveedores.setActionCommand("Proveedores");

        itemGestionarProveedores.setText("Gestionar Proveedores");
        menuProveedores.add(itemGestionarProveedores);

        menuBar.add(menuProveedores);

        menuReportes.setText("Reportes ");

        itemVentasPorFecha.setText("Ventas Por Fecha");
        menuReportes.add(itemVentasPorFecha);

        itemProductosMasVendidos.setText("Productos Mas Vendidos");
        itemProductosMasVendidos.setActionCommand("Productos Mas Vendidos ");
        itemProductosMasVendidos.setAutoscrolls(true);
        menuReportes.add(itemProductosMasVendidos);

        menuBar.add(menuReportes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JMenuItem gestionarEmpleados;
    public javax.swing.JMenuItem itemGestionEmpleados;
    public javax.swing.JMenuItem itemGestionarProveedores;
    public javax.swing.JMenuItem itemProductosMasVendidos;
    public javax.swing.JMenuItem itemVentasPorFecha;
    public javax.swing.JMenuItem itenGestionarProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JLabel lblBienvenida;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuEmpleados;
    public javax.swing.JMenu menuProductos;
    public javax.swing.JMenu menuProveedores;
    public javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
