/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author chaco
 */
public class MenuAdministrador extends javax.swing.JFrame {
Color mColorFondo = new Color(24, 127, 220); //Azul 
Color mColorFondo2 = new Color(93, 173, 226);

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
                this.setLocationRelativeTo(null);
                
        menuProductos.setOpaque(true);
        menuProductos.setBackground(mColorFondo);
        menuProductos.setForeground(Color.white);
        
        menuEmpleados.setOpaque(true);
        menuEmpleados.setBackground(mColorFondo);
        menuEmpleados.setForeground(Color.white);
        
        menuProveedores.setOpaque(true);
        menuProveedores.setBackground(mColorFondo);
        menuProveedores.setForeground(Color.white);
        
        menuReportes.setOpaque(true);
        menuReportes.setBackground(mColorFondo);
        menuReportes.setForeground(Color.white);
  
        itenGestionarProductos.setOpaque(true);
        itenGestionarProductos.setBackground(mColorFondo2);
        itenGestionarProductos.setForeground(Color.white);
        
        itemGestionEmpleados.setOpaque(true);
        itemGestionEmpleados.setBackground(mColorFondo2);
        itemGestionEmpleados.setForeground(Color.white);
        
        itemGestionarProveedores.setOpaque(true);
        itemGestionarProveedores.setBackground(mColorFondo2);
        itemGestionarProveedores.setForeground(Color.white);
        
        itemProductosMasVendidos.setOpaque(true);
        itemProductosMasVendidos.setBackground(mColorFondo2);
        itemProductosMasVendidos.setForeground(Color.white);
        
        itemVentasPorFecha.setOpaque(true);
        itemVentasPorFecha.setBackground(mColorFondo2);
        itemVentasPorFecha.setForeground(Color.white);
        
      ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/img/com.png"));
      ImageIcon icono = new ImageIcon(getClass().getResource("/img/b.png"));
      

      Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
      lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_SMOOTH);

      lblFondo.setIcon(new ImageIcon(imagenEscalada));

      Image imagenEscala = icono.getImage().getScaledInstance(
      lblBienvenida.getWidth(), lblBienvenida.getHeight(), Image.SCALE_SMOOTH);

      lblBienvenida.setIcon(new ImageIcon(imagenEscala));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        gestionarEmpleados = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuEmpleados = new javax.swing.JMenu();
        itemGestionEmpleados = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        itenGestionarProductos = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        itemGestionarProveedores = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemVentasPorFecha = new javax.swing.JMenuItem();
        itemProductosMasVendidos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        gestionarEmpleados.setText("gestionarEmpleados");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrarSesion.setText("Cerar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lblBienvenida.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        lblBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/b.png"))); // NOI18N
        lblBienvenida.setText("Bienvenido...");

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/com.png"))); // NOI18N
        lblFondo.setText("jLabel1");

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(378, 378, 378)
                            .addComponent(btnCerrarSesion)
                            .addGap(18, 18, 18)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCerrarSesion)
                .addGap(25, 25, 25))
        );

        menuBar.setBackground(new java.awt.Color(0, 102, 255));
        menuBar.setBorder(new javax.swing.border.MatteBorder(null));

        menuEmpleados.setBackground(new java.awt.Color(204, 204, 204));
        menuEmpleados.setText("Empleados");

        itemGestionEmpleados.setText("Gestionar Empleados");
        menuEmpleados.add(itemGestionEmpleados);

        menuBar.add(menuEmpleados);

        menuProductos.setText("Productos");

        itenGestionarProductos.setText("Gestionar Productos");
        itenGestionarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itenGestionarProductosActionPerformed(evt);
            }
        });
        menuProductos.add(itenGestionarProductos);

        menuBar.add(menuProductos);

        menuProveedores.setText("Proveedores");

        itemGestionarProveedores.setBackground(new java.awt.Color(51, 153, 255));
        itemGestionarProveedores.setText("Gestionar Proveedores");
        itemGestionarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarProveedoresActionPerformed(evt);
            }
        });
        menuProveedores.add(itemGestionarProveedores);

        menuBar.add(menuProveedores);

        menuReportes.setText("Reportes ");

        itemVentasPorFecha.setText("Ventas Por Fecha");
        menuReportes.add(itemVentasPorFecha);

        itemProductosMasVendidos.setText("Productos Mas Vendidos");
        itemProductosMasVendidos.setActionCommand("Productos Mas Vendidos ");
        itemProductosMasVendidos.setAutoscrolls(true);
        menuReportes.add(itemProductosMasVendidos);

        menuBar.add(menuReportes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void itemGestionarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarProveedoresActionPerformed

    private void itenGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itenGestionarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itenGestionarProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnSalir;
    public javax.swing.JMenuItem gestionarEmpleados;
    public javax.swing.JMenuItem itemGestionEmpleados;
    public javax.swing.JMenuItem itemGestionarProveedores;
    public javax.swing.JMenuItem itemProductosMasVendidos;
    public javax.swing.JMenuItem itemVentasPorFecha;
    public javax.swing.JMenuItem itenGestionarProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblFondo;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuEmpleados;
    public javax.swing.JMenu menuProductos;
    public javax.swing.JMenu menuProveedores;
    public javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
