/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author chaco
 */

import javax.swing.JOptionPane;
import java.sql.Connection;
import DAO.mesaDAO;
import conection.CreateConection;
import Vista.VistaAgregarPedido;
import Vista.MenuMesero;
import javax.swing.table.DefaultTableModel;
import Modelo.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Modelo.ModeloDetallePedido;
import java.util.List;
import DAO.DetallePedidoDAO;
import DAO.PedidoDAO;
import Vista.vistaLogin;

public class MenuMesero extends javax.swing.JFrame {
    private Usuario usuario;
    private int idUsuarioActual;
    /**
     * Creates new form MenuMesero
     */
    public MenuMesero(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        cargarMesas();
        inicializarTablaPedidos(usuario);
        this.setLocationRelativeTo(null);
        
      ImageIcon icono0 = new ImageIcon(getClass().getResource("/Img/b.png"));
      ImageIcon iconoListo = new ImageIcon(getClass().getResource("/Img/pedido.png"));
      ImageIcon iconover = new ImageIcon(getClass().getResource("/Img/ver.png"));
      ImageIcon iconoliberar = new ImageIcon(getClass().getResource("/Img/liberar.png"));
      ImageIcon iconoactualizar = new ImageIcon(getClass().getResource("/Img/actualizar.png"));
      ImageIcon iconobeb = new ImageIcon(getClass().getResource("/Img/beb.png"));
      
      Image imagenEscalas = icono0.getImage().getScaledInstance(
      lblBienvenida.getWidth(), lblBienvenida.getHeight(), Image.SCALE_SMOOTH);

      lblBienvenida.setIcon(new ImageIcon(imagenEscalas));
      
      Image imagenEscala = iconoListo.getImage().getScaledInstance(
      lblListo.getWidth(), lblListo.getHeight(), Image.SCALE_SMOOTH);

      lblListo.setIcon(new ImageIcon(imagenEscala));
      
      Image imagenEscala1 = iconover.getImage().getScaledInstance(
      lblver.getWidth(), lblver.getHeight(), Image.SCALE_SMOOTH);

      lblver.setIcon(new ImageIcon(imagenEscala1));
      
      Image imagenEscala2 = iconoliberar.getImage().getScaledInstance(
      lblLiberar.getWidth(), lblLiberar.getHeight(), Image.SCALE_SMOOTH);

      lblLiberar.setIcon(new ImageIcon(imagenEscala2));
      
        Image imagenEscala3 = iconoactualizar.getImage().getScaledInstance(
      lblActualizar.getWidth(), lblActualizar.getHeight(), Image.SCALE_SMOOTH);

      lblActualizar.setIcon(new ImageIcon(imagenEscala3));
      
      Image imagenEscala4 = iconobeb.getImage().getScaledInstance(
      lblBeb.getWidth(), lblBeb.getHeight(), Image.SCALE_SMOOTH);

      lblBeb.setIcon(new ImageIcon(imagenEscala4));
      
    }
    
    public void inicializarTablaPedidos(Usuario usuario) {
    String[] columnas = { "ID Producto", "Nombre Producto", "Cantidad", "Precio Unitario", "Subtotal" };
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);
    tblMesas.setModel(modelo);
}
    
    private void cargarMesas() {
    cmbMesa.removeAllItems(); 
    cmbMesa.addItem("1");
    cmbMesa.addItem("2");
    cmbMesa.addItem("3");
    cmbMesa.addItem("4");
    cmbMesa.addItem("5");
    cmbMesa.addItem("6");
    cmbMesa.addItem("7");
    cmbMesa.addItem("8");
    cmbMesa.addItem("9");
    cmbMesa.addItem("10");
}
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMesa = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        cmbMesa = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        lblEstadoMesa = new javax.swing.JLabel();
        btnVerPedido = new javax.swing.JButton();
        btnAgregarPedido = new javax.swing.JButton();
        btnLiberarMesa = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        btnCerrarSesion = new javax.swing.JButton();
        lblListo = new javax.swing.JLabel();
        lblver = new javax.swing.JLabel();
        lblLiberar = new javax.swing.JLabel();
        lblBeb = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMesa.setBackground(new java.awt.Color(255, 255, 255));
        lblMesa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMesa.setText("Mesa Seleccionada ");
        jPanel1.add(lblMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, -1));

        lblBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/b.png"))); // NOI18N
        lblBienvenida.setText("Bienvenido...");
        jPanel1.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 320, 60));

        cmbMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatus.setText("Estado");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, -1));

        lblEstadoMesa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEstadoMesa.setText("Libre");
        jPanel1.add(lblEstadoMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 60, -1));

        btnVerPedido.setText("Ver Pedido Actual");
        btnVerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        btnAgregarPedido.setText("Agregar Pedido ");
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 117, -1));

        btnLiberarMesa.setText("Liberar Mesa");
        btnLiberarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarMesaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLiberarMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMesas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 470, 159));

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, -1, -1));

        lblListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pedido.png"))); // NOI18N
        lblListo.setText("jLabel1");
        jPanel1.add(lblListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 40, 40));

        lblver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ver.png"))); // NOI18N
        jPanel1.add(lblver, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 40, 40));

        lblLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/liberar.png"))); // NOI18N
        lblLiberar.setText("jLabel1");
        jPanel1.add(lblLiberar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 40, 40));

        lblBeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/beb.png"))); // NOI18N
        lblBeb.setText("jLabel1");
        jPanel1.add(lblBeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 90, 80));

        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizar.png"))); // NOI18N
        lblActualizar.setText("jLabel1");
        jPanel1.add(lblActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 37, 38));

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLiberarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarMesaActionPerformed
        try {
        int idMesa = cmbMesa.getSelectedIndex() + 1; 

        CreateConection cc = new CreateConection();
        Connection conn = cc.getConnection();

        mesaDAO dao = new mesaDAO(conn);
        dao.liberarMesa(idMesa);

        lblEstadoMesa.setText("Libre");
        JOptionPane.showMessageDialog(this, "Mesa liberada correctamente.");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al liberar la mesa: " + e.getMessage());
    }
    }//GEN-LAST:event_btnLiberarMesaActionPerformed

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
int idMesa = obtenerIdMesaSeleccionada(); 
        int idUsuario = 0;
VistaAgregarPedido agregarPedido;
        try {
            agregarPedido = new VistaAgregarPedido(idMesa, idUsuario, usuario);
            agregarPedido.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuMesero.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void btnVerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidoActionPerformed
   try {
        int idMesa = obtenerIdMesaSeleccionada();
        CreateConection cc = new CreateConection();
        Connection conn = cc.getConnection();

        PedidoDAO pedidoDAO = new PedidoDAO(conn);
        DetallePedidoDAO detalleDAO = new DetallePedidoDAO(conn);

        int idPedido = pedidoDAO.obtenerUltimoPedidoPorMesa(idMesa);
        if (idPedido == -1) {
            JOptionPane.showMessageDialog(this, "No hay pedidos activos para esta mesa.");
            return;
        }

        List<ModeloDetallePedido> detalles = detalleDAO.listarPorPedido(idPedido);
        DefaultTableModel modelo = (DefaultTableModel) tblMesas.getModel();
        modelo.setRowCount(0);  // Limpiar tabla

        for (ModeloDetallePedido d : detalles) {
            modelo.addRow(new Object[]{
                d.getIdProducto(),
                d.getNombreProducto(), // Esto debes obtenerlo del JOIN
                d.getCantidad(),
                d.getPrecioUnitario(),
                d.getSubtotal()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al ver pedido: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnVerPedidoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
          cargarMesas();  
    JOptionPane.showMessageDialog(this, "Mesas actualizadas.");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
 this.dispose();  
 new vistaLogin().setVisible(true); 
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private int obtenerIdMesaSeleccionada() {
    String seleccion = cmbMesa.getSelectedItem().toString();
    return Integer.parseInt(seleccion); 
}
    
    private void abrirVistaAgregarPedido() throws SQLException {
    int idMesa = cmbMesa.getSelectedIndex() + 1; 
    int idMesero = this.idUsuarioActual; 

    VistaAgregarPedido vistaPedido = new VistaAgregarPedido(idMesa, idMesero, usuario);
    vistaPedido.setVisible(true);
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregarPedido;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnLiberarMesa;
    private javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVerPedido;
    public javax.swing.JComboBox<String> cmbMesa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblBeb;
    public javax.swing.JLabel lblBienvenida;
    public javax.swing.JLabel lblEstadoMesa;
    private javax.swing.JLabel lblLiberar;
    private javax.swing.JLabel lblListo;
    public javax.swing.JLabel lblMesa;
    public javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblver;
    public javax.swing.JTable tblMesas;
    // End of variables declaration//GEN-END:variables
}
