/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author chaco
 */
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;
import Modelo.ModeloPedido;
import DAO.PedidoDAO;
import DAO.DetallePedidoDAO;
import DAO.mesaDAO;
import conection.CreateConection;
import java.sql.Connection;
import Modelo.ModeloDetallePedido;


public class VistaAgregarPedido extends javax.swing.JFrame {

private int idMesa;
private int idUsuario;

    /**
     * Creates new form VistaAgregarPedido
     */
    public VistaAgregarPedido(int idMesa, int idUsuario) {
    initComponents();
    
    this.idMesa = idMesa;
    this.idUsuario = idUsuario;

    configurarTabla();
    cargarProductos();
    setLocationRelativeTo(null);
    this.setLocationRelativeTo(null);
    ImageIcon iconovista = new ImageIcon(getClass().getResource("/Img/vistap.png"));
    ImageIcon iconoagr = new ImageIcon(getClass().getResource("/Img/agregar.png"));
    ImageIcon iconoconf = new ImageIcon(getClass().getResource("/Img/confirmar.png"));
    ImageIcon iconocancel = new ImageIcon(getClass().getResource("/Img/eliminar.png"));


    
      Image imagenEscalas = iconovista.getImage().getScaledInstance(
      lblVerp.getWidth(), lblVerp.getHeight(), Image.SCALE_SMOOTH);
      lblVerp.setIcon(new ImageIcon(imagenEscalas));
      
      Image imagenEscala1 = iconoagr.getImage().getScaledInstance(
      lblAgregar.getWidth(), lblAgregar.getHeight(), Image.SCALE_SMOOTH);
      lblAgregar.setIcon(new ImageIcon(imagenEscala1));
      
      Image imagenEscala2 = iconoconf.getImage().getScaledInstance(
      lblConfirmar.getWidth(), lblConfirmar.getHeight(), Image.SCALE_SMOOTH);
      lblConfirmar.setIcon(new ImageIcon(imagenEscala2));
      
      Image imagenEscala3 = iconocancel.getImage().getScaledInstance(
      lblcancelar.getWidth(), lblcancelar.getHeight(), Image.SCALE_SMOOTH);
      lblcancelar.setIcon(new ImageIcon(imagenEscala3));
    }

    
    private void configurarTabla() {
    String[] columnas = { "ID", "Nombre", "Cantidad", "Precio Unitario", "Subtotal" };
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);
    tblDetalle.setModel(modelo);
}
    
   private void cargarProductos() {
    // Simulando lista desde BD - reemplaza con tu DAO real
    cmbProducto.removeAllItems(); // limpia primero

   cmbProducto.addItem("1 - Coca-Cola");
    cmbProducto.addItem("2 - Pepsi");
    cmbProducto.addItem("3 - Jugo de Naranja");
    cmbProducto.addItem("4 - Agua Mineral");
    cmbProducto.addItem("5 - Hamburguesa");
    cmbProducto.addItem("6 - Hot Dog");
    cmbProducto.addItem("7 - Pizza Personal");
    cmbProducto.addItem("8 - Tacos al Pastor");
    cmbProducto.addItem("9 - Pollo Frito");
    cmbProducto.addItem("10 - Ensalada César");
    cmbProducto.addItem("11 - Spaghetti Bolognesa");
    cmbProducto.addItem("12 - Lasagna");
    cmbProducto.addItem("13 - Papas Fritas");
    cmbProducto.addItem("14 - Nachos con Queso");
    cmbProducto.addItem("15 - Helado de Vainilla");
    cmbProducto.addItem("16 - Pie de Manzana");
    cmbProducto.addItem("17 - Pastel de Chocolate");
    cmbProducto.addItem("18 - Flan Casero");
    cmbProducto.addItem("19 - Café Americano");
    cmbProducto.addItem("20 - Té Helado");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        btnConfirmarPedido = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbProducto = new javax.swing.JComboBox<>();
        lblVerp = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        lblConfirmar = new javax.swing.JLabel();
        lblcancelar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setUndecorated(true);

        panel1.setBackground(new java.awt.Color(0, 204, 204));

        tblDetalle.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        lblCantidad.setBackground(new java.awt.Color(0, 0, 0));
        lblCantidad.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad");
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarProducto.setText("Agregar \nProducto");

        btnConfirmarPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmarPedido.setText("Confirmar Pedido");
        btnConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar Pedido");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cmbProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblVerp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/vistap.png"))); // NOI18N
        lblVerp.setText("jLabel1");

        lblProducto.setBackground(new java.awt.Color(0, 0, 0));
        lblProducto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setText("Producto");

        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar.png"))); // NOI18N
        lblAgregar.setText("jLabel1");

        lblConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/confirmar.png"))); // NOI18N
        lblConfirmar.setText("jLabel1");

        lblcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        lblcancelar.setText("jLabel1");

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProducto)
                            .addComponent(lblCantidad)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnConfirmarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProducto, 0, 120, Short.MAX_VALUE)
                            .addComponent(txtCantidad))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblVerp, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblVerp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarPedido)
                    .addComponent(btnAgregarProducto)
                    .addComponent(lblAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(lblcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< Upstream, based on origin/master
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
=======
    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
       try {
    String item = cmbProducto.getSelectedItem().toString();
    String[] partes = item.split(" - ");
    int idProducto = Integer.parseInt(partes[0]);
    String nombre = partes[1];

    int cantidad = Integer.parseInt(txtCantidad.getText());

    // Simular precio
    double precioUnitario = switch (idProducto) {
        case 1 -> 10.0;
        case 2 -> 8.5;
        case 3 -> 5.0;
        case 4 -> 12.0;
        case 5 -> 15.0;
        default -> 9.0;
    };

    double subtotal = cantidad * precioUnitario;

    DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();
    modelo.addRow(new Object[]{ idProducto, nombre, cantidad, precioUnitario, subtotal });

    txtCantidad.setText("");

} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error al agregar producto: " + ex.getMessage());
}
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();

    if (modelo.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Agrega al menos un producto al pedido.");
        return;
    }

    try {
        
        int idUsuario = 1; 
        int idCliente = 1; 
        int idMesa = 1; 

        // Calcular total e impuesto
        double total = 0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            total += Double.parseDouble(modelo.getValueAt(i, 4).toString()); 
        }
        double impuesto = total * 0.15;

        // 1. Insertar en tabla pedidos
        ModeloPedido pedido = new ModeloPedido();
        pedido.setIdCliente(idCliente);
        pedido.setIdUsuario(idUsuario);
        pedido.setMesaId(idMesa);
        pedido.setTotal(total);
        pedido.setImpuesto(impuesto);
        
        CreateConection cc = new CreateConection();
        Connection conn = cc.getConnection();

        PedidoDAO pedidoDAO = new PedidoDAO(conn);
        DetallePedidoDAO detalleDAO = new DetallePedidoDAO(conn);
        mesaDAO mesaDAO = new mesaDAO(conn);

        
        int idPedidoGenerado = pedidoDAO.insertarPedido(pedido);

        // 2. Insertar detalles
       

        for (int i = 0; i < modelo.getRowCount(); i++) {
            ModeloDetallePedido detalle = new ModeloDetallePedido();
            detalle.setIdPedido(idPedidoGenerado);
            detalle.setIdProducto(Integer.parseInt(modelo.getValueAt(i, 0).toString()));
            detalle.setCantidad(Integer.parseInt(modelo.getValueAt(i, 2).toString()));
            detalle.setPrecioUnitario(Double.parseDouble(modelo.getValueAt(i, 3).toString()));
            detalle.setSubtotal(Double.parseDouble(modelo.getValueAt(i, 4).toString()));

            detalleDAO.insertarDetalle(detalle);
        }

        
        
        mesaDAO.ocuparMesa(idMesa);

        JOptionPane.showMessageDialog(this, "Pedido registrado correctamente.");

        modelo.setRowCount(0); // Limpiar tabla

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar el pedido: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();
modelo.setRowCount(0); 
this.dispose(); 
    }//GEN-LAST:event_btnCancelarActionPerformed
>>>>>>> a686fdc nueva actualizacion

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgregarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgregarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgregarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgregarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarProducto;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblVerp;
    private javax.swing.JLabel lblcancelar;
    private java.awt.Panel panel1;
    public javax.swing.JTable tblDetalle;
    public javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
